language: python

python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install .

script:
  - flake8 extended_approval/*.py
  - flake8 contrib/*.py
